googlemaps-samples/android-places-demos

- compat/app/build.gradle
- compat/build.gradle
- demo/app/build.gradle
- demo/app/src/main/java/com/example/placesdemo/AutocompleteTestActivity.java
- demo/app/src/main/java/com/example/placesdemo/CurrentPlaceTestActivity.java
- demo/app/src/main/java/com/example/placesdemo/StringUtil.java
- demo/app/src/main/res/layout/autocomplete_test_activity.xml
- demo/app/src/main/res/values/strings.xml
- demo/build.gradle
> upgrade to 1.1.0

- README.md
- demo/app/build.gradle
- demo/app/src/main/java/com/example/placesdemo/AutocompleteTestActivity.java
- demo/app/src/main/java/com/example/placesdemo/StringUtil.java
- demo/app/src/main/res/layout/autocomplete_test_activity.xml
- demo/gradle.properties
Also fixes confusion raised in Issue #12
> Streamline dependencies and remove deprecated AutocompleteFragment

- compat/app/build.gradle
- compat/app/src/main/java/com/example/placesdemo/MainActivity.java
- compat/app/src/main/res/layout/activity_main.xml
- compat/app/src/main/res/values/strings.xml
- compat/build.gradle
- compat/gradle.properties
- compat/gradle/wrapper/gradle-wrapper.properties
- demo/app/build.gradle
- demo/app/src/main/AndroidManifest.xml
- demo/app/src/main/java/com/example/placesdemo/AutocompleteTestActivity.java
- demo/app/src/main/java/com/example/placesdemo/CurrentPlaceTestActivity.java
- demo/app/src/main/java/com/example/placesdemo/FieldSelector.java
- demo/app/src/main/java/com/example/placesdemo/MainActivity.java
- demo/app/src/main/java/com/example/placesdemo/PlaceAndPhotoTestActivity.java
- demo/app/src/main/java/com/example/placesdemo/StringUtil.java
- demo/app/src/main/res/layout/activity_main.xml
- demo/app/src/main/res/layout/autocomplete_test_activity.xml
- demo/app/src/main/res/layout/current_place_test_activity.xml
- demo/app/src/main/res/layout/place_and_photo_test_activity.xml
- demo/app/src/main/res/values/strings.xml
- demo/app/src/main/res/values/styles.xml
- demo/build.gradle
- demo/gradle.properties
- demo/gradle/wrapper/gradle-wrapper.properties
See [v2.1.0 release notes](https://developers.google.com/places/android-sdk/releases#november_4_2019_-_v210) for newly supported features. Also updates the [compat version](https://github.com/googlemaps/android-places-demos/tree/master/compat) of the sample app.
> Update to Places SDK for Android v2.1.0

- compat/app/build.gradle
- demo/app/build.gradle
- demo/app/src/main/java/com/example/placesdemo/AutocompleteTestActivity.java
- demo/app/src/main/java/com/example/placesdemo/StringUtil.java
- demo/app/src/main/res/layout/autocomplete_test_activity.xml
- demo/app/src/main/res/values/strings.xml
- Add straight line distance to programmatic autocomplete requests
- Add support for restricting Place Autocomplete predictions to multiple countries
See [v2.2.0 release notes](https://developers.google.com/places/android-sdk/releases#february_3_2020_-_v220) for more information.
> feat: Update to Places SDK for Android v2.2.0

- compat/app/src/main/java/com/example/placesdemo/MainActivity.java
- compat/build.gradle
- compat/gradle/wrapper/gradle-wrapper.properties
Fixing build error in `compat` module.
> fix: Fix build error.

- demo-java/app/build.gradle
- demo-java/app/src/main/AndroidManifest.xml
- demo-java/app/src/main/java/com/example/placesdemo/MainActivity.java
- demo-java/app/src/main/java/com/example/placesdemo/programmatic_predictions/PlacePredictionAdapter.java
- demo-java/app/src/main/java/com/example/placesdemo/programmatic_predictions/ProgrammaticAutocompleteToolbarActivity.java
- demo-java/app/src/main/res/drawable/ic_search_black_24dp.xml
- demo-java/app/src/main/res/layout/activity_main.xml
- demo-java/app/src/main/res/layout/activity_programmatic_autocomplete.xml
- demo-java/app/src/main/res/layout/place_prediction_item.xml
- demo-java/app/src/main/res/menu/menu.xml
- demo-java/app/src/main/res/values/strings.xml
- demo-java/build.gradle
- demo-java/gradle/wrapper/gradle-wrapper.properties
- demo-kotlin/app/build.gradle
- demo-kotlin/app/src/main/AndroidManifest.xml
- demo-kotlin/app/src/main/java/com/example/placesdemo/MainActivity.kt
- demo-kotlin/app/src/main/java/com/example/placesdemo/programmatic_predictions/PlacePredictionAdapter.kt
- demo-kotlin/app/src/main/java/com/example/placesdemo/programmatic_predictions/ProgrammaticAutocompleteToolbarActivity.kt
- demo-kotlin/app/src/main/res/drawable/ic_search_black_24dp.xml
- demo-kotlin/app/src/main/res/layout/activity_main.xml
- demo-kotlin/app/src/main/res/layout/activity_programmatic_autocomplete.xml
- demo-kotlin/app/src/main/res/layout/place_prediction_item.xml
- demo-kotlin/app/src/main/res/menu/menu.xml
- demo-kotlin/app/src/main/res/values/strings.xml
Adding `ProgrammaticAutocompleteToolbarActivity` which demonstrates how to implement as-you-type place predictions.
Empty | Searching | Results
:-----:|:------:|:------:
> chore: Adding activity to demonstrate programmatic as-you-type place predictions

- demo-java/app/build.gradle
- demo-kotlin/app/build.gradle
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> chore: Bump Places SDK to 2.4.0

- snippets/app/src/main/java/com/google/places/PlaceAutocompleteActivity.java
Use androidx NonNull instead of NotNull.
> fix: Use androidx NonNull.

- .github/dependabot.yml
- snippets/app/build.gradle
Move region tag maps_android_places_install_snippet. Once merged, I'll delete the `devsite` branch.
> chore: Move maps_android_places_install_snippet region tag

- demo-java/app/build.gradle
- demo-java/app/src/gms/java/com/example/placesdemo/AutocompleteAddressActivity.java
chore: update demo-java to API 30
chore: add region tags for documentation of autocomplete address form sample
Fixes #195
> chore: update demo-java to API 30 and add region tags

- demo-java/app/src/gms/java/com/example/placesdemo/AutocompleteAddressActivity.java
- demo-java/app/src/main/res/layout/autocomplete_address_map.xml
I missed a few tags in PR #197.
> chore: add more region tags to autocomplete address sample

- demo-java/app/build.gradle
- demo-kotlin/app/build.gradle
- demo-kotlin/build.gradle
- snippets/app/build.gradle
- snippets/build.gradle
> chore: Remove jcenter()

- demo-kotlin/app/src/gms/java/com/example/placesdemo/PlaceAndPhotoTestActivity.kt
- demo-kotlin/gradle.properties
- snippets/app/src/main/java/com/google/places/kotlin/PlacesIconActivity.kt
> fix: Build errors.

- snippets/app/build.gradle
- snippets/app/src/main/AndroidManifest.xml
- snippets/app/src/main/java/com/google/places/kotlin/PlaceAutocompleteActivity.kt
- snippets/gradle/wrapper/gradle-wrapper.properties
Adds `maps_android_places_upgrade_snippet` region tag.
> chore: Add maps_android_places_upgrade_snippet region tag.

- demo-java/app/build.gradle
- demo-java/app/src/main/AndroidManifest.xml
- demo-java/build.gradle
- demo-java/gradle/wrapper/gradle-wrapper.properties
- demo-kotlin/app/build.gradle
- demo-kotlin/app/src/main/AndroidManifest.xml
- demo-kotlin/build.gradle
- demo-kotlin/gradle/wrapper/gradle-wrapper.properties
- snippets/app/build.gradle
> chore: Upgrade AGP to 7.1.2.

- demo-java/app/build.gradle
- demo-java/app/src/main/java/com/example/placesdemo/AutocompleteAddressActivity.java
- demo-java/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.java
- demo-java/app/src/main/java/com/example/placesdemo/PlaceAutocompleteActivity.java
- demo-java/app/src/main/java/com/example/placesdemo/PlaceDetailsAndPhotosActivity.java
- demo-kotlin/app/build.gradle
- demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt
- demo-kotlin/app/src/main/java/com/example/placesdemo/PlaceAutocompleteActivity.kt
- demo-kotlin/app/src/main/java/com/example/placesdemo/PlaceDetailsAndPhotosActivity.kt
- demo-kotlin/app/src/main/res/values/strings.xml
The following PR adds view binding and some cleaning to the Places Demos.
> feat: adding view binding to place demos

- snippets/app/src/main/java/com/google/places/CurrentPlaceActivity.java
- snippets/app/src/main/java/com/google/places/PlaceAutocompleteActivity.java
- snippets/app/src/main/java/com/google/places/PlaceDetailsActivity.java
- snippets/app/src/main/java/com/google/places/PlaceIsOpenActivity.java
- snippets/app/src/main/java/com/google/places/PlacePhotosActivity.java
- snippets/app/src/main/java/com/google/places/PlacesIconActivity.java
- snippets/app/src/main/java/com/google/places/kotlin/CurrentPlaceActivity.kt
- snippets/app/src/main/java/com/google/places/kotlin/PlaceAutocompleteActivity.kt
- snippets/app/src/main/java/com/google/places/kotlin/PlaceDetailsActivity.kt
- snippets/app/src/main/java/com/google/places/kotlin/PlacePhotosActivity.kt
- snippets/app/src/main/java/com/google/places/kotlin/PlacesIconActivity.kt
- snippets/app/src/main/java/com/google/places/kotlin/PlacesIsOpenActivity.kt
* add documentation snippets for isOpen in Java and Kotlin
* add missing license headers
> chore: add snippets for isOpen

- snippets/app/src/main/java/com/google/places/kotlin/PlaceIsOpenActivity.kt
PlacesIsOpenAcivity.kt -> PlaceIsOpenActivity.kt
> fix: typo in snippets activity name

- .gitignore
- demo-kotlin/app/build.gradle
- demo-kotlin/app/src/main/java/com/example/placesdemo/AutocompleteAddressActivity.kt
- demo-kotlin/app/src/main/java/com/example/placesdemo/CurrentPlaceActivity.kt
- demo-kotlin/app/src/main/java/com/example/placesdemo/StringUtil.kt
- snippets/app/build.gradle
- TypeFilter to PlaceTypes
- Editorial Summary
- Update demo-kotlin dependency to use `places-ktx` and `maps-utils-ktx`
- fix bug in `StringUtil`
- Update Places install snippet
- migrate to use `secrets.properties` file to store secrets
> feat: add samples for release 3.2.0

- snippets/app/build.gradle
- snippets/build.gradle
Snippets update only; will update demos in separate PR.
> chore: update snippets to v3.3.0

- .github/workflows/build.yml
- snippets/app/build.gradle
- snippets/build.gradle
Don't use a variable in the kotlin bom dependency; specify a version that meets the minimum for the latest version of Places SDK for Android.
> docs: update places install snippet

- .github/workflows/build.yml
This PR updates some of our dependencies on the build Flow.
> chore: flow dependencies updated

- PlaceDetailsUIKit/app/src/main/java/com/example/placedetailsuikit/MainActivity.kt
Used in cl/773749042
Thank you for opening a Pull Request!
---
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> docs: add region tags

- demo-java/gradle/libs.versions.toml
- demo-java/gradle/wrapper/gradle-wrapper.properties
- demo-kotlin/gradle/libs.versions.toml
- demo-kotlin/gradle/wrapper/gradle-wrapper.properties
- snippets/gradle/libs.versions.toml
- snippets/gradle/wrapper/gradle-wrapper.properties
This pull request updates Gradle and various AndroidX dependencies to their latest versions.
> chore(deps): Update Gradle and various AndroidX dependencies

- demo-kotlin/app/src/main/java/com/example/placesdemo/PlaceDetailsAndPhotosActivity.kt
- demo-kotlin/app/src/main/java/com/example/placesdemo/programmatic_autocomplete/PlacePredictionAdapter.kt
- demo-kotlin/app/src/main/java/com/example/placesdemo/programmatic_autocomplete/ProgrammaticAutocompleteGeocodingActivity.kt
- demo-kotlin/app/src/main/res/layout/place_details_and_photos_activity.xml
- demo-kotlin/app/src/main/res/layout/place_prediction_item.xml
- demo-kotlin/app/src/main/res/values/strings.xml
- demo-kotlin/gradle/libs.versions.toml
This pull request introduces several new features and improvements:
- Adds buttons for each Place method, arranged in a grid layout.
- Uses the device's location to bias autocomplete results.
- Corrects KDoc documentation and improves logging.
- Updates the Places SDK usage and applies lint improvements.
- Updates dependencies across the samples.
> Feature branch
